extends Node2D

# Monster class with default values for attributes
class Monster:
	var name: String
	var speed: int = 0
	var level: int = 1
	var magicDefense: int = 0
	var physicDefense: int = 0
	var attackDmg: int = 0
	var magicDmg: int = 0
	var hp: int = 0
	var idle # Assuming animation is a scene resource
	var exp: int = 0
	var gold: int = 0
	var monsterMagicList = []
	var type: String = ""
	var luck: int = 0
	var autoAttackSound = ""
	func _init(params: Dictionary):
		name = params.name
		speed = params.speed if "speed" in params else 0
		level = params.level if "level" in params else 1
		magicDefense = params.magicDefense if "magicDefense" in params else 0
		physicDefense = params.physicDefense if "physicDefense" in params else 0
		attackDmg = params.attackDmg if "attackDmg" in params else 0
		magicDmg = params.magicDmg if "magicDmg" in params else 0
		hp = params.hp if "hp" in params else 0
		idle = params.idle
		exp = params.exp if "exp" in params else 0
		gold =  params.gold if "gold" in params else 0
		luck = params.luck if "luck" in params else 0
		type = params.type if "type" in params else ""
		autoAttackSound = params.autoAttackSound if "autoAttackSound" in params else ""
		monsterMagicList = params.monsterMagicList if "monsterMagicList" in params else []
# Define monsters organized by levels using dictionaries

func calculate_monster_hp(level):
	var baseHp = 100  # Base HP at level 1
	var finalHp = 5000  # Desired HP at level 100
	
	var hpIncreasePerLevel = (finalHp - baseHp) / 99  # Linear increase per level

	var totalHp = baseHp + hpIncreasePerLevel * (level - 1)
	return totalHp
	
	
func calculate_monster_exp(hp):
	var exp = hp/3
	
	return exp
func calculate_monster_gold(hp):
	var gold = hp/5
	
	return gold
func calculate_monster_str(level):
	var baseStr = 50  # Base defense at level 1
	var finalStr = 1000  # Desired defense at level 100
	var strIncreasePerLevel = (finalStr - baseStr) / 99  # Linear increase per level
	
	var totalStr = baseStr + strIncreasePerLevel * (level - 1)
	return totalStr
func calculate_monster_ap(level):
	var baseStr = 5  # Base defense at level 1
	var finalStr = 800  # Desired defense at level 100
	var strIncreasePerLevel = (finalStr - baseStr) / 99  # Linear increase per level
	
	var totalStr = baseStr + strIncreasePerLevel * (level - 1)
	return totalStr
func calculate_speed_for_level(level):
	var baseSpeed = 30.0  # Base speed at level 1
	var speedIncreasePerLevel = 4  # Speed increase per level
	var totalSpeed = baseSpeed + speedIncreasePerLevel * (level - 1)

	return totalSpeed


var magics = {
	"水漫金山":{
		"name": "水漫金山",
		"attackType": "range",
		"damage": 1, 
		"cost": 50,
		"description": "群攻法术",
		"effectArea": "aoe",
		"effectingNum": 2,
		"animationArea":"enemy",
		"audio":"res://Audio/SE/法术12.ogg"
	},
	"水攻":{
		"name": "水攻",
		"attackType": "range",
		"damage": 1.3, 
		"cost": 10,
		"description": "群攻法术",
		"effectArea": "single",
		"effectingNum": 1,
		"animationArea":"enemy",
		"audio":"res://Audio/SE/法术12.ogg"
	},
	"水炮":{
		"name": "水炮",
		"attackType": "range",
		"damage": 1.5, 
		"cost": 10,
		"description": "群攻法术",
		"effectArea": "single",
		"effectingNum": 1,
		"animationArea":"enemy",
		"audio":"res://Audio/SE/法术12.ogg"
	},
	"落岩":{
		"name": "落岩",
		"attackType": "range",
		"damage": 1.3, 
		"cost": 30,
		"description": "群攻法术",
		"effectArea": "single",
		"effectingNum": 1,
		"animationArea":"enemy",
		"audio":"res://Audio/SE/落岩.ogg"
	},	
	"地裂火":{
		"name": "地裂火",
		"attackType": "range",
		"damage": 1.6, 
		"cost": 30,
		"description": "单体法术",
		"effectArea": "single",
		"effectingNum": 1,
		"animationArea":"enemy",
		"audio":"res://Audio/SE/火1.ogg"
	},
	"泰山压顶":{
		"name": "泰山压顶",
		"attackType": "range",
		"damage": 1.2, 
		"cost": 30,
		"description": "单体法术",
		"effectArea": "aoe",
		"effectingNum": 2,
		"animationArea":"enemy",
		"audio": "res://Audio/SE/羊.ogg"
	},
	"狐魅术":{
		"name": "狐魅术",
		"attackType": "range",
		"damage": 1.3, 
		"cost": 30,
		"description": "单体法术",
		"effectArea": "single",
		"effectingNum": 1,
		"animationArea":"enemy",
		"audio": "res://Audio/SE/女-呀.ogg"
	},
	"漫天花雨":{
		"name": "漫天花雨",
		"attackType": "range",
		"damage": 1.1, 
		"cost": 30,
		"hitNum":3,
		"description": "群体法术",
		"effectArea": "aoe",
		"effectingNum": 8,
		"animationArea":"enemy",
		"audio": "res://Audio/SE/鸟语花香.ogg"
	},	
	"静电":{
		"name": "静电",
		"attackType": "range",
		"damage": 1.7, 
		"cost": 50,
		"description": "群体法术",
		"effectArea": "single",
		"effectingNum": 1,
		"animationArea":"enemy",
		"audio": "res://Audio/SE/女妖-法术.ogg"
	},	
	"奔雷":{
		"name": "奔雷",
		"attackType": "range",
		"damage": 1.4, 
		"cost": 50,
		"description": "群体法术",
		"effectArea": "aoe",
		"effectingNum": 3,
		"animationArea":"enemy",
		"audio": "res://Audio/SE/法术3.ogg"
	},	
	"烈火":{
		"name": "烈火",
		"attackType": "range",
		"damage": 1.4, 
		"cost": 50,
		"description": "群体法术",
		"effectArea": "single",
		"effectingNum": 1,
		"animationArea":"enemy",
		"audio": "res://Audio/BGS/火3.ogg"
	},
	"天火陨石":{
		"name": "天火陨石",
		"attackType": "range",
		"damage": 1.5, 
		"cost": 50,
		"description": "群体法术",
		"effectArea": "aoe",
		"effectingNum": 8,
		"animationArea":"enemy",
		"audio": "res://Audio/SE/142-Burst02.ogg"
	},
	"吸魂大法":{
		"name": "吸魂大法",
		"attackType": "debuff",
		"damage": 0, 
		"cost": 50,
		"description": "群体法术",
		"effectArea": "single",
		"effectingNum": 1,
		"animationArea":"enemy",
		"audio": "res://Audio/SE/140-Darkness03.ogg"
	},
	"风雨雷电":{
		"name": "风雨雷电",
		"attackType": "range",
		"damage": 1.7, 
		"cost": 50,
		"description": "群体法术",
		"effectArea": "aoe",
		"effectingNum": 2,
		"animationArea":"enemy",
		"audio": "res://Audio/SE/风 (2).wav"
	},
	"开天辟地":{
		"name": "开天辟地",
		"attackType": "melee",
		"damage": 3, 
		"cost": 50,
		"description": "群体法术",
		"effectArea": "single",
		"effectingNum": 1,
		"animationArea":"enemy",
		"audio": "res://Audio/SE/119-Fire03.ogg"
	},	
	"硝爆":{
		"name": "硝爆",
		"attackType": "range",
		"damage": 3, 
		"cost": 50,
		"description": "群体法术",
		"effectArea": "single",
		"effectingNum": 1,
		"animationArea":"enemy",
		"audio": "res://Audio/SE/049-Explosion02.ogg"
	},		
	"虚沉冰封":{
		"name": "虚沉冰封",
		"attackType": "debuff",
		"debuffType": "ice",
		"damage": 1.9, 
		"cost": 500,
		"duration": 2,
		"description": "群体法术",
		"effectArea": "aoe",
		"effectingNum": 1,
		"animationArea":"enemy",
		"audio": "res://Audio/SE/049-Explosion02.ogg"
	},							
	"双龙戏珠":{
		"name": "双龙戏珠",
		"attackType": "range",
		"debuffType": "ice",
		"damage": 2, 
		"cost": 50,
		"duration": 2,
		"description": "群体法术",
		"effectArea": "single",
		"effectingNum": 1,
		"animationArea":"enemy",
		"audio": "res://Audio/SE/双龙戏猪.ogg"
	},								
	"魔音侵袭":{
		"name": "魔音侵袭",
		"attackType": "range",
		"debuffType": "ice",
		"damage": 1.4, 
		"cost": 50,
		"duration": 2,
		"description": "群体法术",
		"effectArea": "aoe",
		"effectingNum": 8,
		"animationArea":"enemy",
		"audio": "res://Audio/SE/咒语2.ogg"
	},			
	"双生碧击":{
		"name": "双生碧击",
		"attackType": "range",
		"debuffType": "ice",
		"damage": 2.5, 
		"cost": 50,
		"duration": 2,
		"description": "群体法术",
		"effectArea": "aoe",
		"effectingNum": 2,
		"animationArea":"enemy",
		"audio": "res://Audio/SE/140-Darkness03.ogg"
	},	
	"雷击":{
		"name": "雷击",
		"attackType": "range",
		"debuffType": "ice",
		"damage": 1.7, 
		"cost": 50,
		"duration": 2,
		"description": "群体法术",
		"effectArea": "single",
		"effectingNum": 1,
		"animationArea":"enemy",
		"audio": "res://Audio/SE/123-Thunder01.ogg"
	},		
	"水满金山":{
		"name": "水满金山",
		"attackType": "range",
		"debuffType": "ice",
		"damage": 1.5, 
		"cost": 50,
		"duration": 2,
		"description": "群体法术",
		"effectArea": "aoe",
		"effectingNum": 8,
		"animationArea":"enemy",
		"audio": "res://Audio/SE/127-Water02.ogg"
	},	
	"立墓":{
		"name": "立墓",
		"attackType": "range",
		"damage": 2, 
		"cost": 50,
		"duration": 2,
		"description": "群体法术",
		"effectArea": "single",
		"effectingNum": 1,
		"animationArea":"enemy",
		"audio": "res://Audio/SE/127-Water02.ogg"
	},	
	"死亡召唤":{
		"name": "死亡召唤",
		"attackType": "range",
		"damage": 2, 
		"cost": 50,
		"duration": 2,
		"description": "群体法术",
		"effectArea": "aoe",
		"effectingNum": 2,
		"animationArea":"enemy",
		"audio": "res://Audio/SE/127-Water02.ogg"
	},			
	
	
	"血傀":{
		"name": "血傀",
		"attackType": "range",
		"damage": 3, 
		"cost": 50,
		"duration": 2,
		"description": "群体法术",
		"effectArea": "aoe",
		"effectingNum": 2,
		"animationArea":"enemy",
		"audio": "res://Audio/SE/140-Darkness03.ogg"
	},		
	"龙怒":{
		"name": "龙怒",
		"attackType": "range",
		"damage": 3, 
		"cost": 50,
		"duration": 2,
		"description": "群体法术",
		"effectArea": "aoe",
		"effectingNum": 1,
		"animationArea":"enemy",
		"audio": "res://Audio/SE/暴风.ogg"
	},		
			
		
}


var monsters = {
	"传梦":{
		"传梦": Monster.new({
			"name": "传梦",
			"speed": calculate_speed_for_level(99),
			"level": 99,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 50,
			"magicDmg": calculate_monster_ap(3),
			"posi": "middle",
			"hp": calculate_monster_hp(99),
			"exp": calculate_monster_exp(calculate_monster_hp(3)),
			"gold": calculate_monster_gold(calculate_monster_hp(3)),
			"luck": 10,
			"idle": "传梦idle",
			 "monsterMagicList": [
				magics.get("落岩"),
			],
			}),	
	},		
	
	
	
	"东海湾": {
		"海毛虫": Monster.new({
			"name": "海毛虫",
			"speed": calculate_speed_for_level(1),
			"level": 1,
			"magicDefense": 0,
			"physicDefense": 0,
			"attackDmg": 50,
			"magicDmg": calculate_monster_ap(1),
			"hp": calculate_monster_hp(1),
			"exp": calculate_monster_exp(calculate_monster_hp(1)),
			"gold": calculate_monster_gold(calculate_monster_hp(1)),
			"luck": 10,
			"idle": "海毛虫idle",
			 "monsterMagicList": [
				magics.get("落岩"),
			],
			}),
		"大海龟": Monster.new({
			"name": "大海龟",
			"speed":calculate_speed_for_level(3),
			"level": 3,
			"magicDefense":0,
			"physicDefense": 0,
			"attackDmg": 50,
			"magicDmg": calculate_monster_ap(3),
			"luck": 10,
			"hp": calculate_monster_hp(3),
			"exp": calculate_monster_exp(calculate_monster_hp(3)),
			"gold": calculate_monster_gold(calculate_monster_hp(3)),
			"idle": "大海龟idle",
			 "monsterMagicList": [
				magics.get("水攻"),
			],
		}),
	},	
	"巨蛙":{
		"海毛虫": Monster.new({
			"name": "海毛虫",
			"speed": calculate_speed_for_level(3),
			"level": 3,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 50,
			"magicDmg": calculate_monster_ap(3),
			"posi": "middle",
			"hp": calculate_monster_hp(3),
			"exp": calculate_monster_exp(calculate_monster_hp(3)),
			"gold": calculate_monster_gold(calculate_monster_hp(3)),
			"luck": 10,
			"idle": "海毛虫idle",
			 "monsterMagicList": [
				magics.get("落岩"),
			],
			}),
		"巨蛙": Monster.new({
			"name": "巨蛙",
			"speed": calculate_speed_for_level(6),
			"level": 1,
			"magicDefense": 0,
			"physicDefense": 0,
			"attackDmg": 100,
			"magicDmg": calculate_monster_ap(5),
			"hp": 2000,
			"exp": 1000,
			"gold": 1000,
			"luck": 10,
			"idle": "巨蛙idle",
			 "monsterMagicList": [
				magics.get("水攻"),
			],
			}),		
		"大海龟": Monster.new({
			"name": "大海龟",
			"speed":calculate_speed_for_level(4),
			"level": 1,
			"magicDefense":5,
			"physicDefense": 20,
			"attackDmg": 50,
			"magicDmg": calculate_monster_ap(5),
			"hp": calculate_monster_hp(5),
			"exp": calculate_monster_exp(calculate_monster_hp(5)),
			"gold": calculate_monster_gold(calculate_monster_hp(5)),
			"luck": 10,
			"idle": "大海龟idle",
			 "monsterMagicList": [
				magics.get("水攻"),
			],
		}),				
	},	
	"奔霸":{
		"虾兵": Monster.new({
			"name": "虾兵",
			"speed": 30,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 15,
			"magicDmg": 2,
			"hp": 300,
			"exp": 50,
			"gold": 10,
			"idle": "虾兵idle",
			 "monsterMagicList": [
				magics.get("落岩"),
			],
			}),
		"虾兵2": Monster.new({
			"name": "虾兵",
			"speed": 30,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 15,
			"magicDmg": 2,
			"hp": 300,
			"exp": 50,
			"gold": 10,
			"idle": "虾兵idle",
			 "monsterMagicList": [
				magics.get("落岩"),
			],
			}),	
		"虾兵3": Monster.new({
			"name": "虾兵",
			"speed": 30,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 15,
			"magicDmg": 2,
			"hp": 300,
			"exp": 50,
			"gold": 10,
			"idle": "虾兵idle",
			 "monsterMagicList": [
				magics.get("落岩"),
			],
			}),
		"蟹将1": Monster.new({
			"name": "蟹将",
			"speed": 30,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 15,
			"magicDmg": 2,
			"hp": 300,
			"exp": 50,
			"gold": 10,
			"idle": "蟹将idle",
			 "monsterMagicList": [
				magics.get("水攻"),
			],
			}),
		"蟹将2": Monster.new({
			"name": "蟹将",
			"speed": 30,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 15,
			"magicDmg": 2,
			"hp": 300,
			"exp": 50,
			"gold": 10,
			"idle": "蟹将idle",
			 "monsterMagicList": [
				magics.get("水攻"),
			],
			}),	
		"奔霸": Monster.new({
			"name": "奔霸",
			"speed": 40000,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 500,
			"magicDmg": 400,
			"hp": 20000,
			"exp": 50,
			"gold": 10,
			"idle": "奔霸idle",
			 "monsterMagicList": [
				magics.get("水漫金山"),
			],
			}),					
		"蟹将3": Monster.new({
			"name": "蟹将",
			"speed": 30,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 15,
			"magicDmg": 2,
			"hp": 200,
			"exp": 50,
			"gold": 10,
			"idle": "蟹将idle",
			 "monsterMagicList": [
				magics.get("水攻"),
			],
			}),							
	},
	"虾兵蟹将":{
		"虾兵": Monster.new({
			"name": "虾兵",
			"speed": 20,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 55,
			"magicDmg": calculate_monster_ap(2),
			"hp": 300,
			"exp": 50,
			"gold": 10,
			"idle": "虾兵idle",
			 "monsterMagicList": [
				magics.get("落岩"),
			],
			}),
		"虾兵2": Monster.new({
			"name": "虾兵",
			"speed": 20,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 55,
			"magicDmg": calculate_monster_ap(2),
			"hp": 300,
			"exp": 50,
			"gold": 10,
			"idle": "虾兵idle",
			 "monsterMagicList": [
				magics.get("落岩"),
			],
			}),	
		"虾兵3": Monster.new({
			"name": "虾兵",
			"speed": 20,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 55,
			"magicDmg": calculate_monster_ap(2),
			"hp": 300,
			"exp": 50,
			"gold": 10,
			"idle": "虾兵idle",
			 "monsterMagicList": [
				magics.get("落岩"),
			],
			}),
		"蟹将1": Monster.new({
			"name": "蟹将",
			"speed": 20,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 55,
			"magicDmg": calculate_monster_ap(2),
			"hp": 300,
			"exp": 50,
			"gold": 10,
			"idle": "蟹将idle",
			 "monsterMagicList": [
				magics.get("水攻"),
			],
			}),
		"蟹将2": Monster.new({
			"name": "蟹将",
			"speed": 20,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 55,
			"magicDmg": calculate_monster_ap(2),
			"hp": 300,
			"exp": 50,
			"gold": 10,
			"idle": "蟹将idle",
			 "monsterMagicList": [
				magics.get("水攻"),
			],
			}),		
		"蟹将3": Monster.new({
			"name": "蟹将",
			"speed": 20,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 55,
			"magicDmg": calculate_monster_ap(2),
			"hp": 300,
			"exp": 50,
			"gold": 10,
			"idle": "蟹将idle",
			 "monsterMagicList": [
				magics.get("水攻"),
			],
			}),														
	},
	"牛羊怪":{
		"牛妖":Monster.new({
			"name": "牛妖",
			"speed": 50,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 100,
			"magicDmg": calculate_monster_ap(8),
			"hp": 2000,
			"exp": calculate_monster_exp(2000),
			"gold": calculate_monster_gold(2000),
			"idle": "牛妖idle",
			 "monsterMagicList": [
				magics.get("地裂火"),
			],
			}),
		"羊妖":Monster.new({
			"name": "羊妖",
			"speed": 50,
			"level": 8,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 100,
			"magicDmg": calculate_monster_ap(8),
			"hp": 2000,
			"exp": calculate_monster_exp(2000),
			"gold": calculate_monster_gold(2000),
			"idle": "羊妖idle",
			 "monsterMagicList": [
				magics.get("泰山压顶"),
			],
			}),
	},
	"蓝羽妖女":{
		"蓝羽妖女":Monster.new({
			"name": "蓝羽妖女",
			"speed": 120,
			"level": 1,
			"magicDefense": 50,
			"physicDefense": 50,
			"attackDmg": 250,
			"type": "",
			"posi": "middle",
			"magicDmg": 200,
			"hp": 4000,
			"exp": calculate_monster_exp(3500),
			"gold": calculate_monster_gold(3500),
			"idle": "蓝羽妖女idle",
			 "monsterMagicList": [
				magics.get("静电"),
			],
			})},		
	"江南野外": {
		"狐狸精": Monster.new({
			"name": "狐狸精",
			"speed": calculate_speed_for_level(8),
			"level": 8,
			"magicDefense": 5,
			"physicDefense": 30,
			"attackDmg": calculate_monster_str(8),
			"magicDmg": calculate_monster_ap(8),
			"hp": calculate_monster_hp(8),
			"exp": calculate_monster_exp(calculate_monster_hp(8)),
			"gold": calculate_monster_gold(calculate_monster_hp(8)),
			"luck": 10,
			"type": "",
			"idle": "狐狸精idle",
			 "monsterMagicList": [
				magics.get("狐魅术"),
			],
			}),
		"花妖": Monster.new({
			"name": "花妖",
			"speed":calculate_speed_for_level(9),
			"level": 9,
			"magicDefense":5,
			"physicDefense": 30,
			"attackDmg": calculate_monster_str(9),
			"magicDmg": calculate_monster_ap(9),
			"luck": 10,
			"hp": calculate_monster_hp(9),
			"exp": calculate_monster_exp(calculate_monster_hp(9)),
			"gold": calculate_monster_gold(calculate_monster_hp(9)),
			"type": "",
			"idle": "花妖idle",
			 "monsterMagicList": [
				magics.get("漫天花雨"),
			],
		}),
		"牛妖":Monster.new({
			"name": "牛妖",
			"speed": calculate_speed_for_level(10),
			"level": 10,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": calculate_monster_str(10),
			"magicDmg": calculate_monster_ap(10),
			"luck": 10,
			"hp": calculate_monster_hp(10),
			"exp": calculate_monster_exp(calculate_monster_hp(10)),
			"gold": calculate_monster_gold(calculate_monster_hp(10)),
			"type": "",
			"idle": "牛妖idle",
			 "monsterMagicList": [
				magics.get("地裂火"),
			],
			}),
		"羊妖":Monster.new({
			"name": "羊妖",
			"speed": calculate_speed_for_level(10),
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": calculate_monster_str(10),
			"magicDmg": calculate_monster_ap(10),
			"luck": 10,
			"hp": calculate_monster_hp(10),
			"exp": calculate_monster_exp(calculate_monster_hp(10)),
			"gold": calculate_monster_gold(calculate_monster_hp(10)),
			"type": "",
			"idle": "羊妖idle",
			 "monsterMagicList": [
				magics.get("泰山压顶"),
			],
			}),
			
	},
	"大鹏":{
		"大鹏":Monster.new({
			"name": "大鹏",
			"speed": 140,
			"level": 1,
			"magicDefense": 0,
			"physicDefense": 0,
			"attackDmg": 130,
			"magicDmg": 150,
			"hp": 3000,
			"posi": "middle",
			"exp": 400,
			"gold": 1500,
			"idle": "大鹏idle",
			 "monsterMagicList": [
				magics.get("奔雷"),
			],
			"type":""
			})},		
	"牛冠军": {
		"牛冠军": Monster.new({
			"name": "牛冠军",
			"speed": 60,
			"level": 1,
			"magicDefense": 20,
			"physicDefense": 20,
			"attackDmg": 300,
			"magicDmg": 2,
			"exp": 200,
			"posi": "middle",
			"gold": 800,
			"luck": 0,
			"hp": 3000,
			"idle": "牛冠军idle",
			 "monsterMagicList": [
				magics.get("烈火"),
			],	
			"type":""		
		}),
	},
	"鼠先锋": {
		"鼠先锋": Monster.new({
			"name": "鼠先锋",
			"speed": 90,
			"level": 1,
			"magicDefense": 20,
			"physicDefense": 20,
			"attackDmg": 200,
			"magicDmg": 150,
			"posi": "middle",
			"exp": calculate_monster_exp(1800),
			"gold": calculate_monster_gold(1800),
			"hp": 1800,
			"idle": "鼠先锋idle",
			 "monsterMagicList": [
				magics.get("奔雷"),
				magics.get("落岩"),
			],	
			"type":""		
		}),
	},
	"爷傲奈我何": {
		"爷傲奈我何": Monster.new({
			"name": "爷傲奈我何",
			"speed": 60,
			"level": 1,
			"magicDefense": 20,
			"physicDefense": 20,
			"attackDmg": 50,
			"magicDmg": 1,
			"posi": "middle",
			"exp": 150,
			"luck": 10,
			"gold": 80,
			"hp": 600,
			"idle": "爷傲奈我何idle",
			 "monsterMagicList": [
				magics.get("烈火"),
			],
			"type":""		
		}),
	},	
	"锁妖塔2"	:{
		"狐狸精": Monster.new({
			"name": "狐狸精",
			"speed": calculate_speed_for_level(15),
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 30,
			"attackDmg": calculate_monster_str(15),
			"magicDmg": calculate_monster_ap(15),
			"hp": calculate_monster_hp(15),
			"exp": calculate_monster_exp(calculate_monster_hp(15)),
			"luck": 10,
			"gold": calculate_monster_gold(calculate_monster_hp(15)),
			"idle": "狐狸精idle",
			 "monsterMagicList": [
				magics.get("狐魅术"),
			],
			"type":""
			}),
		"花妖": Monster.new({
			"name": "花妖",
			"speed": calculate_speed_for_level(16),
			"level": 16,
			"magicDefense":5,
			"physicDefense": 30,
			"attackDmg": calculate_monster_str(16),
			"magicDmg": calculate_monster_ap(16),
			"hp": calculate_monster_hp(16),
			"exp": calculate_monster_exp(calculate_monster_hp(16)),
			"luck": 10,
			"gold": calculate_monster_gold(calculate_monster_hp(16)),
			"idle": "花妖idle",
			 "monsterMagicList": [
				magics.get("漫天花雨"),
			],
			"type":""
		}),			
	},
	
	"鳄额呃":{
		"鳄额呃": Monster.new({
			"name": "鳄额呃",
			"speed": 160,
			"level": 1,
			"magicDefense":5,
			"physicDefense": 30,
			"attackDmg": 400,
			"magicDmg": 1,
			"posi": "middle",
			"hp": 4500,
			"exp": calculate_monster_exp(4500),
			"luck": 50,
			"gold":calculate_monster_gold(4500),
			"type":"",
			"idle": "鳄额呃idle",
			 "monsterMagicList": [
			],
		}),				
	},
	"锁妖塔3":{
		"牛妖":Monster.new({
			"name": "牛妖",
			"speed": calculate_speed_for_level(17),
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": calculate_monster_str(17),
			"magicDmg": calculate_monster_ap(17),
			"luck": 10,
			"hp": calculate_monster_hp(17),
			"exp": calculate_monster_exp(calculate_monster_hp(17)),
			"gold": calculate_monster_gold(calculate_monster_hp(17)),
			"idle": "牛妖idle",
			"type": "",
			 "monsterMagicList": [
				magics.get("地裂火"),
			],
			}),
		"羊妖":Monster.new({
			"name": "羊妖",
			"speed": calculate_speed_for_level(18),
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": calculate_monster_str(18),
			"magicDmg": calculate_monster_ap(18),
			"luck": 10,
			"hp": calculate_monster_hp(18),
			"exp": calculate_monster_exp(calculate_monster_hp(18)),
			"gold": calculate_monster_gold(calculate_monster_hp(18)),
			"idle": "羊妖idle",
			"type": "",
			 "monsterMagicList": [
				magics.get("泰山压顶"),
			],
			}),
	},
	"鼠老大":{
		"鼠老大": Monster.new({
			"name": "鼠先锋",
			"speed": 170,
			"level": 1,
			"magicDefense":5,
			"physicDefense": 30,
			"attackDmg": 380,
			"posi": "middle",
			"luck": 50,
			"magicDmg": 1.5,
			"hp": 5000,
			"exp": calculate_monster_exp(5000),
			"gold":calculate_monster_gold(5000),
			"type":"",
			"idle": "鼠先锋idle",
			 "monsterMagicList": [
			],
		}),				
	},	
	"锁妖塔4":{
		"兔子精":Monster.new({
			"name": "兔子精",
			"speed": 170,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": calculate_monster_str(19),
			"magicDmg": calculate_monster_ap(19),
			"luck": 10,
			"hp": calculate_monster_hp(19),
			"exp": calculate_monster_exp(calculate_monster_hp(19)),
			"gold": calculate_monster_gold(calculate_monster_hp(19)),
			"idle": "兔子精idle",
			"type": "",
			 "monsterMagicList": [
				magics.get("地裂火"),
			],
			}),
		"黑熊精":Monster.new({
			"name": "黑熊精",
			"speed": calculate_speed_for_level(20),
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": calculate_monster_str(20),
			"magicDmg": calculate_monster_ap(20),
			"luck": 10,
			"hp": calculate_monster_hp(20),
			"exp": calculate_monster_exp(calculate_monster_hp(20)),
			"gold": calculate_monster_gold(calculate_monster_hp(20)),
			"idle": "黑熊精idle",
			"type": "",
			 "monsterMagicList": [
				
			],
			}),
	},	
	"黑熊王":{
		"黑熊王": Monster.new({
			"name": "黑熊王",
			"speed":110,
			"level": 1,
			"magicDefense":5,
			"physicDefense": 30,
			"posi": "middle",
			"attackDmg": 470,
			"magicDmg": 1.5,
			"luck": 50,
			"hp": 5500,
			"exp": calculate_monster_exp(5500),
			"gold": calculate_monster_gold(5500),
			"type":"",
			"idle": "黑熊王idle",
			 "monsterMagicList": [
			],
		}),				
	},		
	"蒙面人":{
		"蒙面人": Monster.new({
			"name": "蒙面人",
			"speed":0,
			"level": 1,
			"magicDefense":5,
			"physicDefense": 30,
			"attackDmg": 190,
			"magicDmg": 1.5,
			"posi": "middle",
			"hp": 1,
			"exp": 1,
			"gold":1,
			"type":"",
			"idle": "蒙面人idle",
			 "monsterMagicList": [
			],
		}),				
	},
	"锁妖塔6":{
		"树怪":Monster.new({
			"name": "树怪",
			"speed": calculate_speed_for_level(21),
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": calculate_monster_str(21),
			"magicDmg": calculate_monster_ap(21),
			"luck": 10,
			"hp": calculate_monster_hp(21),
			"exp": calculate_monster_exp(calculate_monster_hp(21)),
			"gold": calculate_monster_gold(calculate_monster_hp(21)),
			"idle": "树怪idle",
			"type": "",
			 "monsterMagicList": [
			],
			}),
	},	
	"千年树":{
		"千年树": Monster.new({
			"name": "千年树",
			"speed": 140,
			"level": 1,
			"magicDefense":5,
			"posi": "middle",
			"physicDefense": 30,
			"attackDmg": 530,
			"magicDmg": 1.5,
			"hp": 8000,
			"luck": 50,
			"exp": calculate_monster_exp(8000),
			"gold": calculate_monster_gold(8000),
			"type":"",
			"idle": "千年树idle",
			 "monsterMagicList": [
			],
		}),				
	},
	"鹰孽大王":{
		"鹰孽大王": Monster.new({
			"name": "鹰孽大王",
			"speed": 160,
			"level": 1,
			"magicDefense":0,
			"physicDefense": 0,
			"attackDmg": 600,
			"magicDmg": 190,
			"posi": "middle",
			"hp": 9000,
			"exp": calculate_monster_exp(9000),
			"gold": calculate_monster_gold(9000),
			"luck": 65,
			"type":"",
			"idle": "鹰孽大王idle",
			 "monsterMagicList": [
				magics.get("地裂火"),
				magics.get("天火陨石"),
				#magics.get("吸魂大法"),
			],
		}),				
	},
	"大唐国境":{
		"反贼小头目":Monster.new({
			"name": "反贼小头目",
			"speed": 105,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 130,
			"magicDmg": 2,
			"posi": "middle",
			"hp": 600,
			"exp": 60,
			"luck": 20,
			"gold": 40,
			"idle": "反贼小头目idle",
			"type": "",
			 "monsterMagicList": [
				
			],
			}),
		"反贼大头目":Monster.new({
			"name": "反贼大头目",
			"speed": 110,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 130,
			"magicDmg": 2,
			"hp": 850,
			"posi": "middle",
			"exp": 60,
			"luck": 20,
			"gold": 40,
			"idle": "反贼大头目idle",
			"type": "",
			 "monsterMagicList": [
				
			],
			}),
	},
	"反贼小头目":{
		"反贼小头目": Monster.new({
			"name": "反贼小头目",
			"speed": 110,
			"level": 1,
			"magicDefense":0,
			"physicDefense": 0,
			"attackDmg": 150,
			"luck": 30,
			"magicDmg": 2,
			"hp": 3000,
			"posi": "middle",
			"exp": 200,
			"gold": 500,
			"type":"",
			"idle": "反贼小头目idle",
			 "monsterMagicList": [
			],
		}),				
	},
	"反贼大头目":{
		"反贼大头目": Monster.new({
			"name": "反贼大头目",
			"speed": 120,
			"level": 1,
			"luck": 30,
			"magicDefense":0,
			"physicDefense": 0,
			"posi": "middle",
			"attackDmg": 180,
			"magicDmg": 2,
			"hp": 4000,
			"exp": 300,
			"gold": 500,
			"type":"",
			"idle": "反贼大头目idle",
			 "monsterMagicList": [

			],
		}),				
	},
	"堕逝":{
		"堕逝": Monster.new({
			"name": "堕逝",
			"speed": 165,
			"level": 1,
			"magicDefense":0,
			"physicDefense": 0,
			"attackDmg": 320,
			"magicDmg": 175,
			"posi": "middle",
			"hp": 8000,
			"exp": 1000,
			"gold": 2000,
			"type":"",
			"idle": "堕逝idle",
			 "monsterMagicList": [
				magics.get("风雨雷电"),
			],
		}),				
	},
	"程咬金":{
		"程咬金": Monster.new({
			"name": "程咬金",
			"speed": 300,
			"level": 1,
			"magicDefense":0,
			"physicDefense": 0,
			"attackDmg": 1200,
			"magicDmg": 250,
			"luck": 50,
			"hp": 13000,
			"posi": "middle",
			"exp": 0,
			"gold": 0,
			"type":"",
			"idle": "程咬金idle",
			 "monsterMagicList": [
				magics.get("开天辟地")
			],
		}),				
	},	
	"黑山":{
		"黑山": Monster.new({
			"name": "黑山",
			"speed": 200,
			"level": 1,
			"magicDefense": 700,
			"luck": 10,
			"physicDefense": 700,
			"attackDmg": 500,
			"magicDmg": 200 ,
			"hp":  7000,
			"posi": "middle",
			"exp": 4000,
			"gold": 2000,
			"type":"",
			"idle": "黑山idle",
			 "monsterMagicList": [
				magics.get("硝爆")
			],
		}),				
	},
	"小师弟":{
		"小师弟": Monster.new({
			"name": "小师弟",
			"speed": 180,
			"level": 1,
			"magicDefense": 0,
			"physicDefense": 0,
			"attackDmg": 300,
			"magicDmg": 3,
			"hp":  5000,
			"exp": 1000,
			"posi": "middle",
			"gold": 0,
			"type":"",
			"idle": "小师弟idle",
			 "monsterMagicList": [
				magics.get("天火陨石")
			],
		}),				
	},
	"机关人":{
		"机关人": Monster.new({
			"name": "机关人",
			"speed": 160,
			"level": 1,
			"magicDefense": 0,
			"physicDefense": 0,
			"attackDmg": 250,
			"luck": 0,
			"magicDmg": 3,
			"hp":  5000,
			"posi": "middle",
			"exp": 400,
			"gold": 0,
			"type":"",
			"idle": "机关人idle",
			 "monsterMagicList": [
			],
		}),				
	},	
	"东海海道":{
		"虾兵": Monster.new({
			"name": "虾兵",
			"speed": 130,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 205,
			"magicDmg": 8,
			"hp": 2000,
			
			"luck": 10,
			"exp": 150,
			"gold": 100,
			"idle": "虾兵idle",
			 "monsterMagicList": [
				magics.get("落岩"),
			],
			}),

		"蟹将": Monster.new({
			"name": "蟹将",
			"speed": 140,
			"level": 1,
			"magicDefense": 5,
			"luck": 10,
			"physicDefense": 20,
			"attackDmg": 255,
			"magicDmg": 9,
			"hp": 2100,
			"exp": 180,
			"gold": 100,
			"idle": "蟹将idle",
			 "monsterMagicList": [
				magics.get("水漫金山"),
			],
			}),

			},
	"东海海道2":{
		"虾兵": Monster.new({
			"name": "虾兵",
			"speed": 130,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 205,
			"magicDmg": 8,
			"hp": 2000,
			"exp": 150,
			"luck": 10,
			"gold": 100,
			"idle": "虾兵idle",
			 "monsterMagicList": [
				magics.get("落岩"),
			],
			}),

		"蟹将": Monster.new({
			"name": "蟹将",
			"speed": 130,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 255,
			"magicDmg": 8,
			"luck": 10,
			"hp": 2100,
			"exp": 180,
			"gold": 100,
			"idle": "蟹将idle",
			 "monsterMagicList": [
				magics.get("水漫金山"),
			],
			}),
			},
	"东海海道3":{
		"虾兵": Monster.new({
			"name": "虾兵",
			"speed": 130,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 205,
			"luck": 10,
			"magicDmg": 8,
			"hp": 2000,
			"exp": 150,
			"gold": 100,
			"idle": "虾兵idle",
			 "monsterMagicList": [
				magics.get("落岩"),
			],
			}),

		"蟹将": Monster.new({
			"name": "蟹将",
			"speed": 130,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 255,
			"luck": 10,
			"magicDmg": 8,
			"hp": 2100,
			"exp": 180,
			"gold": 100,
			"idle": "蟹将idle",
			 "monsterMagicList": [
				magics.get("水漫金山"),
			],
			}),
			},	
	"敖雨":{
		"敖雨": Monster.new({
			"name": "敖雨",
			"speed": 160,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 400,
			"magicDmg": 4,
			"luck": 50,
			"hp":  18000,
			"posi": "middle",
			"exp": 1500,
			"gold": 1000,
			"type":"",
			"idle": "敖雨idle",
			 "monsterMagicList": [
				magics.get("虚沉冰封"),
				magics.get("水满金山")
			],
		}),				
	},	
	"蟹将":{
		"蟹将": Monster.new({
				"name": "蟹将",
				"speed": 150,
				"level": 1,
				"magicDefense": 5,
				"physicDefense": 200,
				"attackDmg": 300,
				"magicDmg": 10,
				"hp": 10000,
				"luck": 10,
				"exp": 1000,
				"gold": 800,
				"idle": "蟹将idle",
				 "monsterMagicList": [
					magics.get("水攻"),
				],
				})},		
	"虾将":{
		"虾将": Monster.new({
				"name": "虾兵",
				"speed": 160,
				"level": 1,
				"magicDefense": 5,
				"physicDefense": 200,
				"attackDmg": 300,
				"luck": 10,
				"magicDmg": 10,
				"hp": 11000,
				"exp": 1000,
				"gold": 800,
				"idle": "虾兵idle",
				 "monsterMagicList": [
					magics.get("水攻"),
				],
				})},
	"巨蛙兄":{
		"巨蛙": Monster.new({
				"name": "巨蛙",
				"speed": 170,
				"level": 1,
				"magicDefense": 5,
				"physicDefense": 150,
				"attackDmg": 400,
				"magicDmg": 16,
				"posi": "middle",
				"hp": 13000,
				"exp": 1000,
				"luck": 10,
				"gold": 800,
				"idle": "巨蛙idle",
				 "monsterMagicList": [
					magics.get("水漫金山"),
					magics.get("水攻"),
					
				],
				})},				
	"窝壳贝":{
		"窝壳贝": Monster.new({
				"name": "窝壳贝",
				"speed": 160,
				"level": 1,
				"magicDefense": 5,
				"physicDefense": 300,
				"attackDmg": 450,
				"magicDmg": 3,
				"hp": 14000,
				"posi": "middle",
				"exp": 1000,
				"gold": 800,
				"luck": 10,
				"idle": "窝壳贝idle",
				 "monsterMagicList": [
					magics.get("水炮"),
				],
				})},	
	"海夜叉":{
		"海夜叉": Monster.new({
				"name": "海夜叉",
				"speed": 190,
				"level": 1,
				"magicDefense": 5,
				"physicDefense": 300,
				"attackDmg": 600,
				"magicDmg": 2,
				"posi": "middle",
				"hp": 25000,
				"exp": 2000,
				"gold": 1000,
				"luck": 10,
				"idle": "海夜叉idle",
				 "monsterMagicList": [
					magics.get("水炮"),
				],
				})},					
				
				
				
	"龙王们":{
		"龙王1": Monster.new({
				"name": "龙王",
				"speed": 200,
				"level": 1,
				"magicDefense": 5,
				"physicDefense": 350,
				"attackDmg": 450,
				"magicDmg": 1.5,
				"luck": 60,
				"hp": 15000,
				"exp": 2500,
				"gold": 1500,
				"idle": "龙王idle",
				 "monsterMagicList": [
					magics.get("双龙戏珠"),
				],
				}),
		"龙王2": Monster.new({
				"name": "龙王",
				"speed": 200,
				"level": 1,
				"magicDefense": 5,
				"physicDefense": 350,
				"luck": 60,
				"attackDmg": 450,
				"magicDmg": 1.5,
				"hp": 15000,
				"exp": 2500,
				"gold": 1500,
				"idle": "龙王idle",
				 "monsterMagicList": [
					magics.get("双龙戏珠"),
				],
				}),				
		"龙王3": Monster.new({
				"name": "龙王",
				"speed": 200,
				"level": 1,
				"luck": 60,
				"magicDefense": 5,
				"physicDefense": 350,
				"attackDmg": 450,
				"magicDmg": 1.5,
				"hp": 15000,
				"exp": 2500,
				"gold": 1500,
				"idle": "龙王idle",
				 "monsterMagicList": [
					magics.get("双龙戏珠"),
				],
				})				
				
				},					
	"黑蝠":{
		"黑蝠": Monster.new({
				"name": "黑蝠",
				"speed": 180,
				"level": 1,
				"magicDefense": 500,
				"physicDefense": 350,
				"attackDmg": 500,
				"magicDmg": 4,
				"luck": 50,
				"hp": 9000,
				"exp": 2000,
				"posi": "middle",
				"gold": 1500,
				"idle": "黑蝠idle",
				 "monsterMagicList": [
					magics.get("魔音侵袭"),
				],
				}),
			},
	"逆无邪":{
		"逆无邪": Monster.new({
				"name": "逆无邪",
				"speed": 200,
				"level": 1,
				"magicDefense": 100,
				"physicDefense": 150,
				"attackDmg": 600,
				"magicDmg": 4,
				"posi": "middle",
				"luck": 50,
				"hp": 9000,
				"exp": 2000,
				"gold": 1500,
				"idle": "逆无邪idle",
				 "monsterMagicList": [

				],
				}),
			},
	"珍珠姐妹":{
		"珍珠姐妹": Monster.new({
				"name": "珍珠姐妹",
				"speed": 190,
				"level": 1,
				"magicDefense": 100,
				"physicDefense": 150,
				"attackDmg": 600,
				"magicDmg": 1,
				"luck": 50,
				"hp": 15000,
				"exp": 4000,
				"posi": "middle",
				"gold": 3000,
				"idle": "珍珠姐妹idle",
				 "monsterMagicList": [
					magics.get("双生碧击")
				],
				}),
			},			
	"海底迷宫1":{
		"虾兵": Monster.new({
			"name": "虾兵",
			"speed": 120,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 205,
			"luck": 10,
			"magicDmg": 8,
			"hp": 1800,
			"exp": 150,
			"gold": 100,
			"idle": "虾兵idle",
			 "monsterMagicList": [
				magics.get("落岩"),
			],
			}),
		"蟹将": Monster.new({
			"name": "蟹将",
			"speed": 130,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"luck": 10,
			"attackDmg": 255,
			"magicDmg": 8,
			"hp": 2000,
			"exp": 180,
			"gold": 100,
			"idle": "蟹将idle",
			 "monsterMagicList": [
				magics.get("水攻"),
			],
			}),
		"海毛虫": Monster.new({
			"name": "海毛虫",
			"speed": 140,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 200,
			"magicDmg": 6,
			"hp": 1500,
			"exp": 100,
			"gold": 10,
			"luck": 10,
			"idle": "海毛虫idle",
			 "monsterMagicList": [
				magics.get("落岩"),
			],
			}),
		"巨蛙": Monster.new({
			"name": "巨蛙",
			"speed": 150,
			"level": 1,
			"magicDefense": 0,
			"physicDefense": 0,
			"attackDmg": 240,
			"magicDmg": 10,
			"hp": 2200,
			"exp": 300,
			"gold": 1000,
			"luck": 10,
			"idle": "巨蛙idle",
			 "monsterMagicList": [
				magics.get("水漫金山"),
				magics.get("水攻"),
			],
			}),				
			},
	"海底迷宫2":{
		"虾兵": Monster.new({
			"name": "虾兵",
			"speed": 140,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 205,
			"luck": 10,
			"magicDmg": 8,
			"hp": 1800,
			"exp": 150,
			"gold": 100,
			"idle": "虾兵idle",
			 "monsterMagicList": [
				magics.get("落岩"),
			],
			}),
		"蟹将": Monster.new({
			"name": "蟹将",
			"speed": 130,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"luck": 10,
			"attackDmg": 255,
			"magicDmg": 8,
			"hp": 2000,
			"exp": 180,
			"gold": 100,
			"idle": "蟹将idle",
			 "monsterMagicList": [
				magics.get("水攻"),
			],
			}),
		"海毛虫": Monster.new({
			"name": "海毛虫",
			"speed": 120,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 200,
			"magicDmg": 6,
			"hp": 1500,
			"exp": 100,
			"gold": 10,
			"luck": 10,
			"idle": "海毛虫idle",
			 "monsterMagicList": [
				magics.get("落岩"),
			],
			}),
		"巨蛙": Monster.new({
			"name": "巨蛙",
			"speed": 150,
			"level": 1,
			"magicDefense": 0,
			"physicDefense": 0,
			"attackDmg": 240,
			"magicDmg": 10,
			"hp": 2200,
			"exp": 300,
			"gold": 1000,
			"luck": 10,
			"idle": "巨蛙idle",
			 "monsterMagicList": [
				magics.get("水漫金山"),
				magics.get("水攻"),
			],
			}),				
			},	
	"海底迷宫3":{
		"虾兵": Monster.new({
			"name": "虾兵",
			"speed": 150,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 205,
			"luck": 10,
			"magicDmg": 8,
			"hp": 1800,
			"exp": 150,
			"gold": 100,
			"idle": "虾兵idle",
			 "monsterMagicList": [
				magics.get("落岩"),
			],
			}),
		"蟹将": Monster.new({
			"name": "蟹将",
			"speed": 140,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"luck": 10,
			"attackDmg": 255,
			"magicDmg": 8,
			"hp": 2000,
			"exp": 180,
			"gold": 100,
			"idle": "蟹将idle",
			 "monsterMagicList": [
				magics.get("水攻"),
			],
			}),
		"海毛虫": Monster.new({
			"name": "海毛虫",
			"speed": 130,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 200,
			"magicDmg": 6,
			"hp": 1500,
			"exp": 100,
			"gold": 10,
			"luck": 10,
			"idle": "海毛虫idle",
			 "monsterMagicList": [
				magics.get("落岩"),
			],
			}),
		"巨蛙": Monster.new({
			"name": "巨蛙",
			"speed": 150,
			"level": 1,
			"magicDefense": 0,
			"physicDefense": 0,
			"attackDmg": 240,
			"magicDmg": 10,
			"hp": 2200,
			"exp": 300,
			"gold": 1000,
			"luck": 10,
			"idle": "巨蛙idle",
			 "monsterMagicList": [
				magics.get("水漫金山"),
				magics.get("水攻"),
			],
			}),				
			},	
	"海底迷宫4":{
		"虾兵": Monster.new({
			"name": "虾兵",
			"speed": 130,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 205,
			"luck": 10,
			"magicDmg": 8,
			"hp": 1800,
			"exp": 150,
			"gold": 100,
			"idle": "虾兵idle",
			 "monsterMagicList": [
				magics.get("落岩"),
			],
			}),
		"蟹将": Monster.new({
			"name": "蟹将",
			"speed": 140,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"luck": 10,
			"attackDmg": 255,
			"magicDmg": 8,
			"hp": 2000,
			"exp": 180,
			"gold": 100,
			"idle": "蟹将idle",
			 "monsterMagicList": [
				magics.get("水攻"),
			],
			}),
		"海毛虫": Monster.new({
			"name": "海毛虫",
			"speed": 130,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 200,
			"magicDmg": 6,
			"hp": 1500,
			"exp": 100,
			"gold": 10,
			"luck": 10,
			"idle": "海毛虫idle",
			 "monsterMagicList": [
				magics.get("落岩"),
			],
			}),
		"巨蛙": Monster.new({
			"name": "巨蛙",
			"speed": 170,
			"level": 1,
			"magicDefense": 0,
			"physicDefense": 0,
			"attackDmg": 240,
			"magicDmg": 10,
			"hp": 2200,
			"exp": 300,
			"gold": 1000,
			"luck": 10,
			"idle": "巨蛙idle",
			 "monsterMagicList": [
				magics.get("水漫金山"),
				magics.get("水攻"),
			],
			}),				
			},	
	"海底迷宫5":{
		"虾兵": Monster.new({
			"name": "虾兵",
			"speed": 120,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 205,
			"luck": 10,
			"magicDmg": 8,
			"hp": 1800,
			"exp": 150,
			"gold": 100,
			"idle": "虾兵idle",
			 "monsterMagicList": [
				magics.get("落岩"),
			],
			}),
		"蟹将": Monster.new({
			"name": "蟹将",
			"speed": 140,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"luck": 10,
			"attackDmg": 255,
			"magicDmg": 8,
			"hp": 2000,
			"exp": 180,
			"gold": 100,
			"idle": "蟹将idle",
			 "monsterMagicList": [
				magics.get("水攻"),
			],
			}),
		"海毛虫": Monster.new({
			"name": "海毛虫",
			"speed": 120,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 200,
			"magicDmg": 6,
			"hp": 1500,
			"exp": 100,
			"gold": 10,
			"luck": 10,
			"idle": "海毛虫idle",
			 "monsterMagicList": [
				magics.get("落岩"),
			],
			}),
		"巨蛙": Monster.new({
			"name": "巨蛙",
			"speed": 150,
			"level": 1,
			"magicDefense": 0,
			"physicDefense": 0,
			"attackDmg": 240,
			"magicDmg": 10,
			"hp": 2200,
			"exp": 300,
			"gold": 1000,
			"luck": 10,
			"idle": "巨蛙idle",
			 "monsterMagicList": [
				magics.get("水漫金山"),
				magics.get("水攻"),
			],
			}),				
			},																
	"龟丞相":{
		"龟丞相": Monster.new({
			"name": "龟丞相",
			"speed": 140,
			"level": 1,
			"magicDefense": 0,
			"physicDefense": 1000,
			"attackDmg": 205,
			"luck": 10,
			"magicDmg": 20,
			"hp": 20000,
			"posi": "middle",
			"exp": 4000,
			"gold": 2000,
			"idle": "龟丞相idle",
			 "monsterMagicList": [
				magics.get("水漫金山"),
			],
			}),		
		},
		
		
	"花果山":{
		"老虎精": Monster.new({
			"name": "老虎精",
			"speed": 160,
			"level": 1,
			"magicDefense": 100,
			"physicDefense": 100,
			"attackDmg": 300,
			"luck": 10,
			"magicDmg": 2,
			"hp": 1800,
			"exp": 400,
			"gold": 200,
			"idle": "老虎精idle",
			 "monsterMagicList": [
				magics.get("雷击"),
			],
			}),		
		"黑蝠": Monster.new({
				"name": "黑蝠",
				"speed": 180,
				"level": 1,
				"magicDefense": 40,
				"physicDefense": 40,
				"attackDmg": 270,
				"magicDmg": 1.8,
				"luck": 10,
				"hp": 1700,
				"exp": 370,
				"gold": 180,
				"idle": "黑蝠idle",
				 "monsterMagicList": [
					magics.get("魔音侵袭"),
				],
				}),			
			
			
		},		
	"双大鹏":{
		"强壮大鹏": Monster.new({
			"name": "大鹏",
			"speed": 240,
			"level": 1,
			"magicDefense": 100,
			"physicDefense": 100,
			"attackDmg": 300,
			"luck": 40,
			"magicDmg": 7,
			"hp": 6000,
			"exp": 400,
			"gold": 7000,
			"idle": "大鹏idle",
			 "monsterMagicList": [
				magics.get("奔雷"),
			],
			}),		
		"强壮大鹏2": Monster.new({
			"name": "大鹏",
			"speed": 240,
			"level": 1,
			"magicDefense": 100,
			"physicDefense": 100,
			"attackDmg": 300,
			"luck": 40,
			"magicDmg": 7,
			"hp": 6000,
			"exp": 1500,
			"gold": 1000,
			"idle": "大鹏idle",
			 "monsterMagicList": [
				magics.get("奔雷"),
			],
			}),	
		},			
	"双黑蝠":{
		"黑蝠": Monster.new({
				"name": "黑蝠",
				"speed": 190,
				"level": 1,
				"magicDefense": 500,
				"physicDefense": 350,
				"attackDmg": 500,
				"magicDmg": 3.5,
				"luck": 50,
				"hp": 7000,
				"exp": 2000,
				"gold": 1500,
				"idle": "黑蝠idle",
				 "monsterMagicList": [
					magics.get("魔音侵袭"),
				],
				}),
		"黑蝠2": Monster.new({
				"name": "黑蝠",
				"speed": 190,
				"level": 1,
				"magicDefense": 500,
				"physicDefense": 350,
				"attackDmg": 500,
				"magicDmg": 3.5,
				"luck": 50,
				"hp": 7000,
				"exp": 2000,
				"gold": 1500,
				"idle": "黑蝠idle",
				 "monsterMagicList": [
					magics.get("魔音侵袭"),
				],
				}),				
				
				
			},
	"兔子精":{
		"兔子精":Monster.new({
			"name": "兔子精",
			"speed": 210,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 430,
			"magicDmg": 8,
			"hp": 8500,
			"luck": 50,
			"exp": 2300,
			"posi": "middle",
			"gold": 1700,
			"idle": "兔子精idle",
			"type": "",
			 "monsterMagicList": [
				magics.get("地裂火"),
			],
			}),	
			},
	"蛤蟆精":{
		"蛤蟆精":Monster.new({
			"name": "蛤蟆精",
			"speed": 190,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 430,
			"magicDmg": 1.2,
			"posi": "middle",
			"hp": 9000,
			"luck": 50,
			"exp": 2500,
			"gold": 2000,
			"idle": "蛤蟆精idle",
			"type": "",
			 "monsterMagicList": [
				magics.get("水满金山"),
			],
			}),	
			},			
	"奔霸2":{
		"奔霸": Monster.new({
			"name": "奔霸",
			"speed": 190,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 700,
			"magicDmg": 3.5,
			"hp": 40000,
			"posi": "middle",
			"exp": 8000,
			"gold": 5000,
			"idle": "奔霸idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),
			},
	"奔霸3":{
		"奔霸": Monster.new({
			"name": "奔霸",
			"speed": 200,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 900,
			"posi": "middle",
			"magicDmg": 5,
			"hp": 100000,
			"exp": 16000,
			"gold": 10000,
			"idle": "奔霸idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),
			},					
	"奔霸4":{
		"奔霸": Monster.new({
			"name": "奔霸",
			"speed": 30,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 600,
			"posi": "middle",
			"magicDmg": 3,
			"hp": 2,
			"exp": 100,
			"gold": 100,
			"idle": "奔霸idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),
			},		
			
			
			
	"怨蛛":{
		"怨蛛": Monster.new({
			"name": "怨蛛",
			"speed": 190,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 300,
			"attackDmg": 700,
			"posi": "middle",
			"magicDmg": 3,
			"hp": 7000,
			"exp": 1250,
			"gold": 750,
			"idle": "怨蛛idle",
			 "monsterMagicList": [
			],
			}),
			},		
	"野鬼":{
			"野鬼": Monster.new({
			"name": "野鬼",
			"speed": 170,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 600,
			"posi": "middle",
			"magicDmg": 3,
			"hp": 2200,
			"exp": 700,
			"gold": 550,
			"type": "鬼",
			"idle": "野鬼idle",
			 "monsterMagicList": [
			],
			}),
			"野鬼2": Monster.new({
			"name": "野鬼",
			"speed": 170,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 600,
			"posi": "middle",
			"magicDmg": 3,
			"hp": 2200,
			"exp": 700,
			"gold": 550,
			"type": "鬼",
			"idle": "野鬼idle",
			 "monsterMagicList": [
			],
			}),			
			"野鬼3": Monster.new({
			"name": "野鬼",
			"speed": 170,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 600,
			"posi": "middle",
			"magicDmg": 3,
			"hp": 2200,
			"exp": 700,
			"gold": 550,
			"type": "鬼",
			"idle": "野鬼idle",
			 "monsterMagicList": [
			],
			}),			
	}	,	
						
	"初鬼":{
		"野鬼": Monster.new({
			"name": "野鬼",
			"speed": 210,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 600,
			"posi": "middle",
			"magicDmg": 3,
			"hp": 2200,
			"exp": 700,
			"gold": 550,
			"type": "鬼",
			"idle": "野鬼idle",
			 "monsterMagicList": [
			],
			}),
		"野鬼1": Monster.new({
			"name": "野鬼",
			"speed": 210,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 600,
			"posi": "middle",
			"magicDmg": 3,
			"hp": 2200,
			"exp": 700,
			"gold": 550,
			"type": "鬼",
			"idle": "野鬼idle",
			 "monsterMagicList": [
			],
			}),	
		"野鬼2": Monster.new({
			"name": "野鬼",
			"speed": 210,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 600,
			"posi": "middle",
			"magicDmg": 3,
			"hp": 2200,
			"exp": 700,
			"gold": 550,
			"type": "鬼",
			"idle": "野鬼idle",
			 "monsterMagicList": [
			],
			}),		
		"骷髅": Monster.new({
			"name": "骷髅",
			"speed": 200,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 650,
			"posi": "middle",
			"magicDmg": 3,
			"hp": 2300,
			"exp": 700,
			"gold": 600,
			"type": "鬼",
			"idle": "骷髅idle",
			 "monsterMagicList": [
			],
			}),
						
			
			
			
			},					
	"地府迷宫1":{
		"野鬼": Monster.new({
			"name": "野鬼",
			"speed": 160,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 500,
			"posi": "middle",
			"magicDmg": 3,
			"hp": 2200,
			"exp": 700,
			"gold": 550,
			"type": "鬼",
			"idle": "野鬼idle",
			 "monsterMagicList": [
				magics.get("死亡召唤"),
			],
			}),
		"骷髅": Monster.new({
			"name": "骷髅",
			"speed": 170,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 550,
			"posi": "middle",
			"magicDmg": 3,
			"hp": 2300,
			"exp": 700,
			"gold": 600,
			"type": "鬼",
			"idle": "骷髅idle",
			 "monsterMagicList": [
				magics.get("立墓"),
			],
			}),
			},					
	"地府迷宫2":{
		"野鬼": Monster.new({
			"name": "野鬼",
			"speed": 160,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 550,
			"posi": "middle",
			"magicDmg": 3,
			"hp": 2400,
			"exp": 800,
			"gold": 550,
			"type": "鬼",
			"idle": "野鬼idle",
			 "monsterMagicList": [
				magics.get("死亡召唤"),
			],
			}),
		"骷髅": Monster.new({
			"name": "骷髅",
			"speed": 170,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 555,
			"posi": "middle",
			"magicDmg": 3,
			"hp": 2500,
			"exp": 900,
			"gold": 600,
			"type": "鬼",
			"idle": "骷髅idle",
			 "monsterMagicList": [
				magics.get("立墓"),
			],
			}),
		"马面": Monster.new({
			"name": "马面",
			"speed": 170,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 665,
			"posi": "middle",
			"magicDmg": 3.2,
			"hp": 3000,
			"exp": 1200,
			"gold": 800,
			"type": "鬼",
			"idle": "马面idle",
			 "monsterMagicList": [
			],
			}),			
			
			
			},					
	"地府迷宫3":{
		"野鬼": Monster.new({
			"name": "野鬼",
			"speed": 170,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 580,
			"posi": "middle",
			"magicDmg": 3,
			"hp": 2500,
			"exp": 850,
			"gold": 550,
			"type": "鬼",
			"idle": "野鬼idle",
			 "monsterMagicList": [
				magics.get("死亡召唤"),
			],
			}),
		"骷髅": Monster.new({
			"name": "骷髅",
			"speed": 180,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 620,
			"posi": "middle",
			"magicDmg": 3,
			"hp": 2600,
			"exp": 950,
			"gold": 600,
			"type": "鬼",
			"idle": "骷髅idle",
			 "monsterMagicList": [
								magics.get("立墓"),
			],
			}),
		"马面": Monster.new({
			"name": "马面",
			"speed": 170,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 705,
			"posi": "middle",
			"magicDmg": 3.2,
			"hp": 3000,
			"exp": 1200,
			"gold": 800,
			"type": "鬼",
			"idle": "马面idle",
			 "monsterMagicList": [
			],
			}),					
		"牛头": Monster.new({
			"name": "牛头",
			"speed": 175,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 715,
			"posi": "middle",
			"magicDmg": 3.3,
			"hp": 3100,
			"exp": 1300,
			"gold": 000,
			"type": "鬼",
			"idle": "牛头idle",
			 "monsterMagicList": [
			],
			}),					
			},					
	"地府迷宫4":{
		"野鬼": Monster.new({
			"name": "野鬼",
			"speed": 190,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 600,
			"posi": "middle",
			"magicDmg": 3,
			"hp": 3000,
			"exp": 1000,
			"gold": 550,
			"type": "鬼",
			"idle": "野鬼idle",
			 "monsterMagicList": [
				magics.get("死亡召唤"),
			],
			}),
		"骷髅": Monster.new({
			"name": "骷髅",
			"speed": 200,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 650,
			"posi": "middle",
			"magicDmg": 3,
			"hp": 2800,
			"exp": 1100,
			"gold": 600,
			"type": "鬼",
			"idle": "骷髅idle",
			 "monsterMagicList": [
								magics.get("立墓"),
			],
			}),
		"马面": Monster.new({
			"name": "马面",
			"speed": 180,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 705,
			"posi": "middle",
			"magicDmg": 3.2,
			"hp": 3000,
			"exp": 1200,
			"gold": 800,
			"type": "鬼",
			"idle": "马面idle",
			 "monsterMagicList": [
			],
			}),					
		"牛头": Monster.new({
			"name": "牛头",
			"speed": 180,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 715,
			"posi": "middle",
			"magicDmg": 3.3,
			"hp": 3100,
			"exp": 1300,
			"gold": 000,
			"type": "鬼",
			"idle": "牛头idle",
			 "monsterMagicList": [
			],
			}),					
			},					
	"地府监狱":{
		"野鬼": Monster.new({
			"name": "野鬼",
			"speed": 190,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 600,
			"posi": "middle",
			"magicDmg": 3,
			"hp": 3200,
			"exp": 1200,
			"gold": 550,
			"type": "鬼",
			"idle": "野鬼idle",
			 "monsterMagicList": [
				magics.get("死亡召唤"),
			],
			}),
		"骷髅": Monster.new({
			"name": "骷髅",
			"speed": 205,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 650,
			"posi": "middle",
			"magicDmg": 3,
			"hp": 3300,
			"exp": 1200,
			"gold": 600,
			"type": "鬼",
			"idle": "骷髅idle",
			 "monsterMagicList": [
								magics.get("立墓"),
			],
			}),
		"马面": Monster.new({
			"name": "马面",
			"speed": 180,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 705,
			"posi": "middle",
			"magicDmg": 3.2,
			"hp": 3000,
			"exp": 1200,
			"gold": 800,
			"type": "鬼",
			"idle": "马面idle",
			 "monsterMagicList": [
			],
			}),					
		"牛头": Monster.new({
			"name": "牛头",
			"speed": 180,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 715,
			"posi": "middle",
			"magicDmg": 3.3,
			"hp": 3100,
			"exp": 1300,
			"gold": 000,
			"type": "鬼",
			"idle": "牛头idle",
			 "monsterMagicList": [
			],
			}),					
			},					
						
	"机关兽":{
		"机关兽": Monster.new({
			"name": "机关兽",
			"speed": 50,
			"level": 1,
			"magicDefense": 0,
			"physicDefense": 0,
			"attackDmg": 40,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 600,
			"exp": 100,
			"gold": 100,
			"type": "",
			"idle": "机关兽idle",
			 "monsterMagicList": [
			],
			}),
			},				
	"鬼将军":{
		"鬼将军": Monster.new({
			"name": "鬼将军",
			"speed": 210,
			"level": 1,
			"magicDefense": 0,
			"physicDefense": 600,
			"attackDmg": 1000,
			"magicDmg": 2.5,
			"posi": "middle",
			"hp": 26000,
			"exp": 20000,
			"gold": 7000,
			"type": "鬼",
			"idle": "鬼将军idle",
			 "monsterMagicList": [
				magics.get("血傀"),				
			],
			}),
			},		
		
			
			
			
	"鬼王":{
		"鬼王": Monster.new({
			"name": "鬼王",
			"speed": 270,
			"level": 1,
			"magicDefense":600,
			"physicDefense": 500,
			"attackDmg": 850,
			"magicDmg": 400,
			"posi": "middle",
			"hp": 60000,
			"exp": 14000,
			"gold": 8000,
			"type": "鬼",
			"idle": "鬼王idle",
			 "monsterMagicList": [
				
			],
			}),
			},					
			
	"噬天虎":{
		"噬天虎": Monster.new({
			"name": "噬天虎",
			"speed": 180,
			"level": 1,
			"magicDefense":300,
			"physicDefense": 300,
			"attackDmg": 650,
			"magicDmg": 40,
			"posi": "middle",
			"hp": 17000,
			"exp": 000,
			"gold": 000,
			"type": "",
			"idle": "噬天虎idle",
			 "monsterMagicList": [
				
			],
			}),
			},					
	"大唐国境边缘":{
		"野猪": Monster.new({
			"name": "野猪",
			"speed": 120,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 205,
			"luck": 10,
			"magicDmg": 8,
			"hp": 1800,
			"exp": 150,
			"gold": 100,
			"idle": "野猪idle",
			 "monsterMagicList": [
				magics.get("落岩"),
			],
			}),
		"蝶妖": Monster.new({
			"name": "蝶妖",
			"speed": 130,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"luck": 10,
			"attackDmg": 255,
			"magicDmg": 8,
			"hp": 2000,
			"exp": 180,
			"gold": 100,
			"idle": "蝶妖idle",
			 "monsterMagicList": [
				magics.get("水攻"),
			],
			}),
			},						
	"大唐境外":{
		"野猪": Monster.new({
			"name": "野猪",
			"speed": 120,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 205,
			"luck": 10,
			"magicDmg": 8,
			"hp": 1800,
			"exp": 150,
			"gold": 100,
			"idle": "野猪idle",
			 "monsterMagicList": [
				magics.get("落岩"),
			],
			}),
		"蝶妖": Monster.new({
			"name": "蝶妖",
			"speed": 130,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"luck": 10,
			"attackDmg": 255,
			"magicDmg": 8,
			"hp": 2000,
			"exp": 180,
			"gold": 100,
			"idle": "蝶妖idle",
			 "monsterMagicList": [
				magics.get("水攻"),
			],
			}),
		"巨石怪": Monster.new({
			"name": "巨石怪",
			"speed": 130,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"luck": 10,
			"attackDmg": 255,
			"magicDmg": 8,
			"hp": 2000,
			"exp": 180,
			"gold": 100,
			"idle": "巨石怪idle",
			 "monsterMagicList": [
				magics.get("水攻"),
			],
			}),			
			},						
	"大唐境外南":{
		"野猪": Monster.new({
			"name": "野猪",
			"speed": 120,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"attackDmg": 205,
			"luck": 10,
			"magicDmg": 8,
			"hp": 1800,
			"exp": 150,
			"gold": 100,
			"idle": "野猪idle",
			 "monsterMagicList": [
				magics.get("落岩"),
			],
			}),
		"蝶妖": Monster.new({
			"name": "蝶妖",
			"speed": 130,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"luck": 10,
			"attackDmg": 255,
			"magicDmg": 8,
			"hp": 2000,
			"exp": 180,
			"gold": 100,
			"idle": "蝶妖idle",
			 "monsterMagicList": [
				magics.get("水攻"),
			],
			}),
		"巨石怪": Monster.new({
			"name": "蝶妖",
			"speed": 130,
			"level": 1,
			"magicDefense": 5,
			"physicDefense": 20,
			"luck": 10,
			"attackDmg": 255,
			"magicDmg": 8,
			"hp": 2000,
			"exp": 180,
			"gold": 100,
			"idle": "蝶妖idle",
			 "monsterMagicList": [
				magics.get("水攻"),
			],
			}),			
			},	
	"青面兽":{
		"青面兽": Monster.new({
			"name": "青面兽",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"gold": 100,
			"idle": "青面兽idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),
			},			
	"白虎":{
		"白虎": Monster.new({
			"name": "白虎",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"gold": 100,
			"idle": "白虎idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),
			},	
	"北俱芦洲":{
		"白熊": Monster.new({
			"name": "白熊",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 4000,
			"exp": 100,
			"gold": 100,
			"idle": "白熊idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),
		"白泽": Monster.new({
			"name": "白泽",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 4000,
			"exp": 100,
			"gold": 100,
			"idle": "白泽idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),			
			
			
			},				
	"凤巢1":{
		"凤凰": Monster.new({
			"name": "凤凰",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"gold": 100,
			"idle": "凤凰idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),
		"蝶妖": Monster.new({
			"name": "蝶妖",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"gold": 100,
			"idle": "蝶妖idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),			
		"幻花": Monster.new({
			"name": "幻花",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"gold": 100,
			"idle": "凤凰idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),			
			
			},	
	"凤巢2":{
		"凤凰": Monster.new({
			"name": "凤凰",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"gold": 100,
			"idle": "凤凰idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),
		"蝶妖": Monster.new({
			"name": "蝶妖",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"gold": 100,
			"idle": "蝶妖idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),			
		"幻花": Monster.new({
			"name": "幻花",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"gold": 100,
			"idle": "凤凰idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),			
			
			},	
	"凤巢3":{
		"凤凰": Monster.new({
			"name": "凤凰",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"gold": 100,
			"idle": "凤凰idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),
		"蝶妖": Monster.new({
			"name": "蝶妖",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"gold": 100,
			"idle": "蝶妖idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),			
		"幻花": Monster.new({
			"name": "幻花",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"gold": 100,
			"idle": "凤凰idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),			
			
			},	
	"凤巢4":{
		"凤凰": Monster.new({
			"name": "凤凰",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"gold": 100,
			"idle": "凤凰idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),
		"蝶妖": Monster.new({
			"name": "蝶妖",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"gold": 100,
			"idle": "蝶妖idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),			
		"幻花": Monster.new({
			"name": "幻花",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"gold": 100,
			"idle": "凤凰idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),			
			
			},																	
	"凤巢5":{
		"凤凰": Monster.new({
			"name": "凤凰",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"gold": 100,
			"idle": "凤凰idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),
		"蝶妖": Monster.new({
			"name": "蝶妖",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"gold": 100,
			"idle": "蝶妖idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),			
		"幻花": Monster.new({
			"name": "幻花",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"gold": 100,
			"idle": "凤凰idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),			
			
			},	
	"凤巢6":{
		"凤凰": Monster.new({
			"name": "凤凰",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"gold": 100,
			"idle": "凤凰idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),
		"蝶妖": Monster.new({
			"name": "蝶妖",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"gold": 100,
			"idle": "蝶妖idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),			
		"幻花": Monster.new({
			"name": "幻花",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"gold": 100,
			"idle": "凤凰idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),			
			
			},	
	"凤巢7":{
		"凤凰": Monster.new({
			"name": "凤凰",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"gold": 100,
			"idle": "凤凰idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),
		"蝶妖": Monster.new({
			"name": "蝶妖",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"gold": 100,
			"idle": "蝶妖idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),			
		"幻花": Monster.new({
			"name": "幻花",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"gold": 100,
			"idle": "凤凰idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),			
			
			},	
	"龙窟1":{
		"蛟龙": Monster.new({
			"name": "蛟龙",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"type": "龙",
			"gold": 100,
			"idle": "蛟龙idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),
		"麒麟": Monster.new({
			"name": "麒麟",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"type": "龙",
			"gold": 100,
			"idle": "麒麟idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),			
		"修罗": Monster.new({
			"name": "修罗",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"gold": 100,
			"idle": "修罗idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),			
			
			},	
	"龙窟2":{
		"蛟龙": Monster.new({
			"name": "蛟龙",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"type": "龙",
			"gold": 100,
			"idle": "蛟龙idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),
		"麒麟": Monster.new({
			"name": "麒麟",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"type": "龙",
			"gold": 100,
			"idle": "麒麟idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),			
		"修罗": Monster.new({
			"name": "修罗",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"gold": 100,
			"idle": "修罗idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),			
			
			},																							
	"龙窟3":{
		"蛟龙": Monster.new({
			"name": "蛟龙",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"type": "龙",
			"gold": 100,
			"idle": "蛟龙idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),
		"麒麟": Monster.new({
			"name": "麒麟",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"type": "龙",
			"gold": 100,
			"idle": "麒麟idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),			
		"修罗": Monster.new({
			"name": "修罗",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"gold": 100,
			"idle": "修罗idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),			
			
			},							
	"龙窟4":{
		"蛟龙": Monster.new({
			"name": "蛟龙",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"type": "龙",
			"gold": 100,
			"idle": "蛟龙idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),
		"麒麟": Monster.new({
			"name": "麒麟",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"type": "龙",
			"gold": 100,
			"idle": "麒麟idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),			
		"修罗": Monster.new({
			"name": "修罗",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"gold": 100,
			"idle": "修罗idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),			
			
			},							
	"龙窟5":{
		"蛟龙": Monster.new({
			"name": "蛟龙",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"type": "龙",
			"gold": 100,
			"idle": "蛟龙idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),
		"麒麟": Monster.new({
			"name": "麒麟",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"type": "龙",
			"gold": 100,
			"idle": "麒麟idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),			
		"修罗": Monster.new({
			"name": "修罗",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"gold": 100,
			"idle": "修罗idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),			
			
			},				
	"龙窟6":{
		"蛟龙": Monster.new({
			"name": "蛟龙",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"type": "龙",
			"gold": 100,
			"idle": "蛟龙idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),
		"麒麟": Monster.new({
			"name": "麒麟",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"type": "龙",
			"gold": 100,
			"idle": "麒麟idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),			
		"修罗": Monster.new({
			"name": "修罗",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"gold": 100,
			"idle": "修罗idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),			
			
			},	
	"龙窟7":{
		"蛟龙": Monster.new({
			"name": "蛟龙",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"type": "龙",
			"gold": 100,
			"idle": "蛟龙idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),
		"麒麟": Monster.new({
			"name": "麒麟",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"type": "龙",
			"gold": 100,
			"idle": "麒麟idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),			
		"修罗": Monster.new({
			"name": "修罗",
			"speed": 100,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 40000,
			"exp": 100,
			"gold": 100,
			"idle": "修罗idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),			
			
			},				
																		
	"青龙":{
		"青龙": Monster.new({
			"name": "青龙",
			"speed": 280,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 1600,
			"magicDmg": 300,
			"posi": "middle",
			"hp": 30000,
			"exp": 100,
			"gold": 100,
			"type": "龙",
			"idle": "青龙idle",
			"autoAttackSound":"res://Audio/SE/085-Monster07.ogg",
			 "monsterMagicList": [
				magics.get("龙怒"),
			
			],
			}),
			},
	"人形青龙":{
		"人形青龙": Monster.new({
			"name": "人形青龙",
			"speed": 240,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 1200,
			"magicDmg": 500,
			"posi": "middle",
			"hp": 80000,
			"exp": 100,
			"gold": 100,
			"type": "龙",
			"idle": "人形青龙idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),
			},		
			
			
			
			
	"镰魔":{
		"镰魔": Monster.new({
			"name": "镰魔",
			"speed": 400,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 1500,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 30000,
			"exp": 0,
			"gold": 0,
			"type": "",
			"idle": "镰魔idle",
			 "monsterMagicList": [
			],
			}),
			},				
	"关重七伤势":{
		"关重七伤势": Monster.new({
			"name": "关重七伤势",
			"speed": 200,
			"level": 1,
			"magicDefense": 0,
			"physicDefense": 0,
			"attackDmg": 800,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 4000,
			"exp": 500,
			"gold": 0,
			"type": "",
			"idle": "关重七伤势idle",
			 "monsterMagicList": [
			],
			}),
			},				
	"瑞兽":{
		"瑞兽": Monster.new({
			"name": "瑞兽",
			"speed": 280,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 1600,
			"magicDmg": 300,
			"posi": "middle",
			"hp": 300,
			"exp": 100,
			"gold": 100,
			"type": "龙",
			"idle": "瑞兽idle",
			"autoAttackSound":"res://Audio/SE/085-Monster07.ogg",
			 "monsterMagicList": [
				magics.get("龙怒"),
			
			],
			}),
			},			
			
					
	"金翅大鹏":{
		"金翅大鹏": Monster.new({
			"name": "金翅大鹏",
			"speed": 500,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 10000,
			"magicDmg": 10000,
			"posi": "middle",
			"hp": 50000,
			"exp": 100,
			"gold": 100,
			"idle": "金翅大鹏idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),
			},				
	"怪僧":{
		"怪僧": Monster.new({
			"name": "怪僧",
			"speed": 500,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 10000,
			"magicDmg": 10000,
			"posi": "middle",
			"hp": 10,
			"exp": 100,
			"gold": 100,
			"idle": "怪僧idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),
			},					
	"罗非":{
		"罗非": Monster.new({
			"name": "罗非",
			"speed": 500,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 10000,
			"magicDmg": 10000,
			"posi": "middle",
			"hp": 10,
			"exp": 100,
			"gold": 100,
			"idle": "罗非idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),
			},
	"弥勒佛":{
		"弥勒佛": Monster.new({
			"name": "弥勒佛",
			"speed": 500,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 10000,
			"magicDmg": 10000,
			"posi": "middle",
			"hp": 10,
			"exp": 100,
			"gold": 100,
			"idle": "弥勒佛idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),
			},			
	"鬼帝":{
		"鬼帝": Monster.new({
			"name": "鬼帝",
			"speed": 500,
			"level": 1,
			"magicDefense": 200,
			"physicDefense": 200,
			"attackDmg": 0,
			"magicDmg": 0,
			"posi": "middle",
			"hp": 100000,
			"exp": 100,
			"gold": 100,
			"idle": "鬼帝idle",
			 "monsterMagicList": [
				magics.get("水满金山"),
				magics.get("水炮"),
			],
			}),
			},										
		}	



# Function to get monsters by level
func get_monsters_by_level(level: String) -> Dictionary:
	return monsters.get(level, {})

func getBoss(bossName) -> Dictionary:
	return monsters.get(bossName, {})




# 以下是不做多个场景的只切换动画
#var monsters = {
#    1: {
#        "huLiJing": {
#            "name": "huLiJing",
#            "age": 30,
#            "city": "New York",
#            "animation": preload("res://path/to/huLiJing_animation.tres")  # Replace with the actual path to your Animation resource
#        },
#        "laoShuJing": {
#            "name": "laoShuJing",
#            "age": 30,
#            "city": "New York",
#            "animation": preload("res://path/to/laoShuJing_animation.tres")  # Replace with the actual path to your Animation resource
#        }
#        # Add more monsters as needed
#    },
#    2: {
#        "laoHuJing": {
#            "name": "laoHuJing",
#            "age": 30,
#            "city": "New York",
#            "animation": preload("res://path/to/laoHuJing_animation.tres")  # Replace with the actual path to your Animation resource
#        }
#        # Add more monsters as needed
#    }
#    # Add more levels as needed
#}
#}
func _process(delta):
	pass

